/**
 * sentimentDataset.js - Dataset pré-étiqueté pour l'entraînement du classifieur de sentiment
 * 
 * Structure:
 * - 166 phrases positives (label: 0)
 * - 162 phrases négatives (label: 1)
 * - 150 phrases neutres (label: 2)
 * Total: 478 phrases
 * 
 * Points clés:
 * - Diversité: phrases courtes, longues, variées, avec fautes volontaires
 * - Contexte: feedback utilisateur, satisfaction client
 * - Labels en index: 0=positif, 1=négatif, 2=neutre
 */

export const sentimentDataset = [
  // ===== PHRASES POSITIVES (LABEL: 0) =====
  { text: "C'est fantastique, j'adore ce produit!", label: 0 },
  { text: "Excellent service, je suis très satisfait.", label: 0 },
  { text: "Bravo, c'est exactement ce qu'il me fallait!", label: 0 },
  { text: "Super, ça marche parfaitement bien.", label: 0 },
  { text: "Je recommande vivement, c'est formidable.", label: 0 },
  { text: "Magnifique, vraiment impressionné!", label: 0 },
  { text: "Adorable, j'en suis très content.", label: 0 },
  { text: "Fabuleux, au-delà de mes attentes.", label: 0 },
  { text: "C'est merveilleux, merci beaucoup!", label: 0 },
  { text: "Absolument génial, cinq étoiles!", label: 0 },
  { text: "Phénoménal, c'est du jamais vu.", label: 0 },
  { text: "Sensationnel, je suis ravi.", label: 0 },
  { text: "Excellent choix, très satisfait.", label: 0 },
  { text: "Splendide, c'est parfait.", label: 0 },
  { text: "Fantastique, vraiment super.", label: 0 },
  { text: "Merveilleux service, très heureux.", label: 0 },
  { text: "Incroyable, exactement ce que je voulais.", label: 0 },
  { text: "Impeccable, aucune déception.", label: 0 },
  { text: "Formidable, vous êtes les meilleurs.", label: 0 },
  { text: "Exceptionnel, au top.", label: 0 },
  { text: "Génial, je ne peux pas te remercier assez.", label: 0 },
  { text: "Fabuleux produit, vraiment content.", label: 0 },
  { text: "Superbe, dépasse les attentes.", label: 0 },
  { text: "Magnifique qualité, j'adore.", label: 0 },
  { text: "Extraordinaire, merci!", label: 0 },
  { text: "Je suis enchanté, c'est super.", label: 0 },
  { text: "Brillant, vraiment bien pensé.", label: 0 },
  { text: "Admirable, j'en suis fasciné.", label: 0 },
  { text: "Superbe expérience, à refaire!", label: 0 },
  { text: "Excellent, continuez comme ça.", label: 0 },
  { text: "Ravissant, c'est magnifique.", label: 0 },
  { text: "Merveilleux, merci de votre aide.", label: 0 },
  { text: "Fantastique qualité, très content.", label: 0 },
  { text: "Adorable, vraiment parfait.", label: 0 },
  { text: "Splendide, vous êtes formidables.", label: 0 },
  { text: "Prodigieux, c'est incroyable.", label: 0 },
  { text: "Sublime, j'en suis très fier.", label: 0 },
  { text: "Exemplaire, bravo à l'équipe.", label: 0 },
  { text: "Merveilleux, vraiment une joie.", label: 0 },
  { text: "Fantastique, c'est du haut niveau.", label: 0 },
  { text: "C'est trop bien, on adore!", label: 0 },
  { text: "Super produit, vraiment top.", label: 0 },
  { text: "Génial, ça change ma vie.", label: 0 },
  { text: "Merveilleux, à recommander.", label: 0 },
  { text: "Excellent, pas de soucis.", label: 0 },
  { text: "Magnifique, je reviendrais.", label: 0 },
  { text: "Fabuleux, vraiment heureux.", label: 0 },
  { text: "Fantastique, dépassé mon attente.", label: 0 },
  { text: "Merveilleux, merci beaucoup.", label: 0 },
  { text: "Superbe, très satisfait.", label: 0 },
  { text: "Excellent, cinq étoiles.", label: 0 },
  { text: "Adorable service, très content.", label: 0 },
  { text: "Bravo, continuez!", label: 0 },
  { text: "Splendide, vraiment au top.", label: 0 },
  { text: "Merveilleux, c'est magique.", label: 0 },
  { text: "Fantastique, tout simplement bien.", label: 0 },
  { text: "C'est magnifique, merci!", label: 0 },
  { text: "Incroyable, j'adore trop.", label: 0 },
  { text: "Super bien, je suis content.", label: 0 },
  { text: "Génial, c'est ouf!", label: 0 },
  { text: "Excellent, j'en suis fier.", label: 0 },
  { text: "Merveilleux, quel bonheur!", label: 0 },
  { text: "Fantastique, tu es le meilleur!", label: 0 },
  { text: "Superbe, c'est formidable.", label: 0 },
  { text: "Magnifique, merci de tout cœur.", label: 0 },
  { text: "Je suis vraiment impressionné par la qualité.", label: 0 },
  { text: "Ça fonctionne à merveille, je suis bluffé.", label: 0 },
  { text: "Livraison rapide, produit conforme, parfait!", label: 0 },
  { text: "Je suis agréablement surpris, c'est top.", label: 0 },
  { text: "Un sans-faute, je suis aux anges.", label: 0 },
  { text: "Rien à redire, tout est nickel.", label: 0 },
  { text: "Je l'utilise tous les jours, c'est indispensable.", label: 0 },
  { text: "On m'a conseillé ce produit, je ne regrette pas.", label: 0 },
  { text: "Ma commande est arrivée rapidement, super content.", label: 0 },
  { text: "Le rapport qualité-prix est imbattable.", label: 0 },
  { text: "Je suis fan, vraiment top notch.", label: 0 },
  { text: "Ça m'a changé la vie, je l'adore.", label: 0 },
  { text: "Très bonne expérience, je reviendrai.", label: 0 },
  { text: "Personnel accueillant et professionnel, bravo!", label: 0 },
  { text: "Je ne m'attendais pas à une telle qualité, époustouflant.", label: 0 },
  { text: "Livré à l'heure, emballage soigné, c'est super.", label: 0 },
  { text: "Vraiment satisfait, aucun problème rencontré.", label: 0 },
  { text: "C'est exactement comme décrit, je suis content.", label: 0 },
  { text: "Très fiable, ça tient ses promesses.", label: 0 },
  { text: "J'ai adoré l'expérience du début à la fin.", label: 0 },
  { text: "Superbe rapport qualité-prix, je recommande.", label: 0 },
  { text: "Je suis épaté, c'est vraiment de la belle ouvrage.", label: 0 },
  { text: "Produit durable et bien conçu, très satisfait.", label: 0 },
  { text: "L'assistance client est au top, merci!", label: 0 },
  { text: "Je suis conquis, vraiment une belle découverte.", label: 0 },
  { text: "Ça dépasse toutes mes espérances, fantastique.", label: 0 },
  { text: "Très bonne prise en main, j'adore.", label: 0 },
  { text: "Je recommande les yeux fermés, c'est parfait.", label: 0 },
  { text: "Fonctionne parfaitement, aucun bug, super.", label: 0 },
  { text: "Un produit de qualité, je suis ravi de mon achat.", label: 0 },
  { text: "Je suis très heureux de ce choix, bravo.", label: 0 },
  { text: "Tout s'est passé comme prévu, c'est formidable.", label: 0 },
  { text: "Vraiment au-delà de mes espoirs, merci.", label: 0 },
  { text: "Super service après-vente, très réactif.", label: 0 },
  { text: "Je suis trop content, c'est vraiment bien.", label: 0 },
  { text: "Ça fait exactement ce qu'on attend, super.", label: 0 },
  { text: "Interface intuitive et agréable, j'adore.", label: 0 },
  { text: "Très bonne qualité de fabrication, bravo.", label: 0 },
  { text: "Je suis pleinement satisfait, rien à signaler.", label: 0 },
  { text: "C'est le meilleur achat que j'ai fait cette année.", label: 0 },
  { text: "Parfait pour mes besoins, je suis très content.", label: 0 },
  { text: "Produit conforme à la description, super.", label: 0 },
  { text: "Je le conseille vivement à tout le monde.", label: 0 },
  { text: "Ça fonctionne impeccablement, vraiment top.", label: 0 },
  { text: "J'ai été séduit dès la première utilisation.", label: 0 },
  { text: "Très bonne expérience client, à refaire.", label: 0 },
  { text: "Je suis enchanté par ce produit, merci.", label: 0 },
  { text: "C'est brillant, je l'adopte définitivement.", label: 0 },
  { text: "Une vraie réussite, je suis bluffé.", label: 0 },
  { text: "Nickel du début à la fin, je recommande.", label: 0 },
  { text: "Je suis très agréablement surpris, super qualité.", label: 0 },
  { text: "Tout fonctionne à la perfection, je suis ravi.", label: 0 },
  { text: "J'adore vraiment ce produit, il est top.", label: 0 },
  { text: "Vraiment bien, je ne regrette pas mon achat.", label: 0 },
  { text: "Super efficace et facile à utiliser, bravo.", label: 0 },
  { text: "C'est une très belle surprise, je suis content.", label: 0 },
  { text: "Je valide à 100%, c'est vraiment excellent.", label: 0 },
  { text: "Je suis totalement satisfait, rien à redire.", label: 0 },
  { text: "Ça dépasse largement mes attentes, super.", label: 0 },
  { text: "Je l'ai recommandé à mes amis tellement c'est bien.", label: 0 },
  { text: "Très content de mon achat, vraiment top.", label: 0 },
  { text: "C'est vraiment une excellente solution.", label: 0 },
  { text: "Je suis satisfait à 100%, vraiment super.", label: 0 },
  { text: "Super pratique et efficace, j'adore.", label: 0 },
  { text: "Un produit fiable et de qualité, bravo.", label: 0 },
  { text: "Je suis super content, c'est parfaitement bien.", label: 0 },
  { text: "Vraiment de la qualité, je suis impressionné.", label: 0 },
  { text: "Expérience utilisateur excellente, très satisfait.", label: 0 },
  { text: "Je suis ravi, le produit est au top.", label: 0 },
  { text: "Bravo pour la qualité, c'est vraiment bien fait.", label: 0 },
  { text: "Je suis très content de cette découverte.", label: 0 },
  { text: "Ça fonctionne super bien, je recommande.", label: 0 },
  { text: "Très bon produit, rapport qualité-prix parfait.", label: 0 },
  { text: "Je suis fan de ce produit, il est génial.", label: 0 },
  { text: "Excellent sous tous les aspects, vraiment top.", label: 0 },
  { text: "Je suis bluffé par la qualité, c'est incroyable.", label: 0 },
  { text: "C'est ce que je cherchais depuis longtemps, parfait.", label: 0 },
  { text: "Livraison express, produit parfait, je suis heureux.", label: 0 },
  { text: "Je suis vraiment très content, c'est top.", label: 0 },
  { text: "Superbe produit, je suis complètement séduit.", label: 0 },
  { text: "Je recommande chaudement, c'est vraiment super.", label: 0 },
  { text: "Une expérience parfaite, je reviendrai.", label: 0 },
  { text: "Je suis conquis par la qualité, bravo.", label: 0 },
  { text: "C'est un vrai bonheur à utiliser.", label: 0 },
  { text: "Très belle qualité, rien à redire.", label: 0 },
  { text: "Je suis heureux de mon achat, c'est parfait.", label: 0 },
  { text: "Ça marche parfaitement, je suis comblé.", label: 0 },
  { text: "Je suis super satisfait, c'est vraiment top.", label: 0 },
  { text: "Parfait, nickel, je recommande vivement.", label: 0 },
  { text: "Très satisfait de l'achat, je reviendrai.", label: 0 },
  { text: "Un achat que je ne regrette pas du tout.", label: 0 },
  { text: "Je suis tellement content, c'est génial.", label: 0 },
  { text: "C'est vraiment top, je suis heureux.", label: 0 },
  { text: "Super bien fait, je suis impressionné.", label: 0 },
  { text: "C'est exactement ce qu'il me fallait, bravo.", label: 0 },
  { text: "Vraiment super, je le recommande à tous.", label: 0 },
  { text: "Je suis très content du résultat, excellent.", label: 0 },
  { text: "C'est parfait, ça répond à tous mes besoins.", label: 0 },
  { text: "Je suis très impressionné, c'est au-delà de mes attentes.", label: 0 },
  { text: "Ça marche vraiment bien, je suis satisfait.", label: 0 },
  { text: "Je suis absolument ravi, c'est top.", label: 0 },

  // ===== PHRASES NÉGATIVES (LABEL: 1) =====
  { text: "C'est horrible, je suis très déçu.", label: 1 },
  { text: "Nul, c'est une vraie catastrophe.", label: 1 },
  { text: "Décevant, ça ne marche pas du tout.", label: 1 },
  { text: "Affreux, c'est injustifiable.", label: 1 },
  { text: "Terrible, je ne recommande pas.", label: 1 },
  { text: "Abominable, c'est vraiment mauvais.", label: 1 },
  { text: "Ignoble, c'est une arnaque.", label: 1 },
  { text: "Pire que prévu, très mécontent.", label: 1 },
  { text: "Horreur, c'est inacceptable.", label: 1 },
  { text: "Catastrophique, j'ai horreur.", label: 1 },
  { text: "Désastreux, c'est un cauchemar.", label: 1 },
  { text: "Exécrable, vraiment pourri.", label: 1 },
  { text: "Détestable, c'est débile.", label: 1 },
  { text: "Répugnant, je suis furieux.", label: 1 },
  { text: "Scandaleux, c'est inadmissible.", label: 1 },
  { text: "Offensant, c'est un vrai problème.", label: 1 },
  { text: "Pathétique, vraiment nulle.", label: 1 },
  { text: "Ridicule, c'est de la merde.", label: 1 },
  { text: "Misérable, c'est trash.", label: 1 },
  { text: "Pitoyable, super mauvais.", label: 1 },
  { text: "Horrible, c'est vraiment nul.", label: 1 },
  { text: "Atroce, je suis très en colère.", label: 1 },
  { text: "Dégueulasse, c'est écœurant.", label: 1 },
  { text: "Répulsif, je déteste tellement.", label: 1 },
  { text: "Immonde, c'est complètement pourri.", label: 1 },
  { text: "Abject, vraiment très mauvais.", label: 1 },
  { text: "Infâme, c'est une arnaque totale.", label: 1 },
  { text: "Déplorable, c'est un désastre.", label: 1 },
  { text: "Indigne, je suis dégoûté.", label: 1 },
  { text: "Sordide, c'est vraiment de la merde.", label: 1 },
  { text: "Vile, c'est débile et nul.", label: 1 },
  { text: "Infecte, c'est une vraie connerie.", label: 1 },
  { text: "Méprisable, je suis très fâché.", label: 1 },
  { text: "Repoussant, c'est vraiment mauvais.", label: 1 },
  { text: "Révoltant, c'est inacceptable.", label: 1 },
  { text: "C'est pour les conards, vraiment nul.", label: 1 },
  { text: "Piraté, c'est du poison.", label: 1 },
  { text: "Pourri, tu es vraiment débile.", label: 1 },
  { text: "Caca, c'est vraiment pourri.", label: 1 },
  { text: "Zéro, c'est la pire connerie.", label: 1 },
  { text: "Dégueulasse produit, j'ai horreur.", label: 1 },
  { text: "C'est trash, vraiment mauvais.", label: 1 },
  { text: "Horrible, ne pas acheter.", label: 1 },
  { text: "Nul, c'est une blague.", label: 1 },
  { text: "Pourquoi j'ai acheté ça, c'est nul.", label: 1 },
  { text: "Perte de temps, vraiment mauvais.", label: 1 },
  { text: "C'est pas bon, déçu.", label: 1 },
  { text: "Horrible expérience, très en colère.", label: 1 },
  { text: "C'est de la merde, vraiment nul.", label: 1 },
  { text: "Pas du tout satisfait, c'est nul.", label: 1 },
  { text: "Décevant au possible, très mécontent.", label: 1 },
  { text: "Catastrophique, j'ai envie de pleurer.", label: 1 },
  { text: "Horrible, c'est un vrai piège.", label: 1 },
  { text: "Détestable, je regrette.", label: 1 },
  { text: "Nul à chier, très fâché.", label: 1 },
  { text: "C'est pourri, c'est la pire chose.", label: 1 },
  { text: "Abysmal, je suis déçu.", label: 1 },
  { text: "Mauvais, vraiment mauvais.", label: 1 },
  { text: "Horrible, ne le faites pas.", label: 1 },
  { text: "C'est de l'arnaque, très déçu.", label: 1 },
  { text: "Abominable, pire jamais.", label: 1 },
  { text: "Terrible, c'est un cauchemar.", label: 1 },
  { text: "Nul, c'est pire que d'attendre.", label: 1 },
  { text: "Je suis très déçu, ça ne correspond pas du tout.", label: 1 },
  { text: "Produit de très mauvaise qualité, je regrette.", label: 1 },
  { text: "Le service client est catastrophique, aucune aide.", label: 1 },
  { text: "C'est cassé à la livraison, inacceptable.", label: 1 },
  { text: "Je n'ai jamais été aussi déçu, c'est une arnaque.", label: 1 },
  { text: "Livraison en retard et produit endommagé, nul.", label: 1 },
  { text: "C'est du foutage de gueule, je suis furieux.", label: 1 },
  { text: "Ça ne marche pas depuis le premier jour.", label: 1 },
  { text: "Je veux un remboursement, c'est inadmissible.", label: 1 },
  { text: "Jamais vu une qualité aussi médiocre.", label: 1 },
  { text: "C'est une déception totale, je ne reviendrai pas.", label: 1 },
  { text: "Produit non conforme à la description, arnaque.", label: 1 },
  { text: "Je suis en colère, on m'a menti.", label: 1 },
  { text: "Service déplorable, aucune réponse du support.", label: 1 },
  { text: "C'est une perte d'argent, vraiment mauvais.", label: 1 },
  { text: "Je suis outré par ce que j'ai reçu.", label: 1 },
  { text: "Ça tombe en panne après deux jours, nul.", label: 1 },
  { text: "Je ne recommande à personne, c'est horrible.", label: 1 },
  { text: "C'est le pire achat de ma vie, je suis enragé.", label: 1 },
  { text: "Qualité nulle, service nul, tout est nul.", label: 1 },
  { text: "Je suis dégoûté, ce produit est une escroquerie.", label: 1 },
  { text: "Ça ne fonctionne pas correctement, très décevant.", label: 1 },
  { text: "J'aurais dû m'abstenir, c'est vraiment nul.", label: 1 },
  { text: "Très mauvaise expérience, je suis mécontent.", label: 1 },
  { text: "C'est du n'importe quoi, je suis hors de moi.", label: 1 },
  { text: "Le produit est arrivé cassé, c'est une honte.", label: 1 },
  { text: "Je suis déçu par la qualité, vraiment décevant.", label: 1 },
  { text: "Ce n'est pas du tout ce qui était annoncé.", label: 1 },
  { text: "Je vais déposer une plainte, c'est inadmissible.", label: 1 },
  { text: "Une vraie catastrophe, je suis scandalisé.", label: 1 },
  { text: "Ne faites pas confiance à ce vendeur, arnaque.", label: 1 },
  { text: "Je suis très fâché, on ne m'a pas remboursé.", label: 1 },
  { text: "Produit inutilisable, j'ai gaspillé mon argent.", label: 1 },
  { text: "C'est lamentable, je suis vraiment déçu.", label: 1 },
  { text: "Horrible à utiliser, interface nulle.", label: 1 },
  { text: "C'est de la camelote, je suis furieux.", label: 1 },
  { text: "Je suis très mécontent, ça ne marche pas.", label: 1 },
  { text: "Une vraie arnaque, je déconseille vivement.", label: 1 },
  { text: "Je regrette profondément cet achat.", label: 1 },
  { text: "Produit dangereux et de mauvaise qualité, nul.", label: 1 },
  { text: "Je suis épouvanté par la médiocrité.", label: 1 },
  { text: "Ça s'est cassé après une semaine, scandaleux.", label: 1 },
  { text: "C'est absolument nul, je suis très déçu.", label: 1 },
  { text: "Je suis indigné, c'est une tromperie.", label: 1 },
  { text: "Très mauvais produit, à éviter absolument.", label: 1 },
  { text: "Je suis exaspéré par le service client.", label: 1 },
  { text: "C'est la pire chose que j'ai achetée.", label: 1 },
  { text: "Ne perdez pas votre argent, c'est de la merde.", label: 1 },
  { text: "Je suis hors de moi, c'est une arnaque.", label: 1 },
  { text: "Vraiment nul, j'ai honte d'avoir acheté ça.", label: 1 },
  { text: "C'est une blague de mauvais goût, très décevant.", label: 1 },
  { text: "Je suis frustré, ça ne fait pas ce qu'on dit.", label: 1 },
  { text: "Une déception immense, je suis très mécontent.", label: 1 },
  { text: "C'est nul, ça m'a coûté de l'argent pour rien.", label: 1 },
  { text: "Je suis très en colère, produit de mauvaise qualité.", label: 1 },
  { text: "C'est de la camelote, vraiment décevant.", label: 1 },
  { text: "Je me sens floué, c'est une escroquerie.", label: 1 },
  { text: "Très déçu, c'est un mauvais investissement.", label: 1 },
  { text: "C'est franchement nul, je suis dégoûté.", label: 1 },
  { text: "Je ne reviendrai jamais, service catastrophique.", label: 1 },
  { text: "Produit de mauvaise qualité, je suis en colère.", label: 1 },
  { text: "C'est honteux, je suis très déçu.", label: 1 },
  { text: "Je suis vraiment mécontent, c'est inacceptable.", label: 1 },
  { text: "Très mauvaise expérience, à éviter.", label: 1 },
  { text: "Je n'aurais pas dû acheter ça, c'est nul.", label: 1 },
  { text: "C'est de la foutaise, je suis furieux.", label: 1 },
  { text: "Je suis complètement déçu, vraiment mauvais.", label: 1 },
  { text: "Ça ne vaut rien, c'est une arnaque.", label: 1 },
  { text: "Je suis très déçu de la qualité, vraiment nul.", label: 1 },
  { text: "C'est pitoyable, je suis scandalisé.", label: 1 },
  { text: "Je suis outré, on m'a vendu de la camelote.", label: 1 },
  { text: "Très nul, je ne le recommande à personne.", label: 1 },
  { text: "Je suis vraiment en colère, c'est inadmissible.", label: 1 },
  { text: "C'est une vraie déception, je suis très fâché.", label: 1 },
  { text: "Produit inutilisable, service nul, je suis déçu.", label: 1 },
  { text: "Je suis très mécontent, c'est une mauvaise qualité.", label: 1 },
  { text: "C'est horrible, je suis vraiment mécontent.", label: 1 },
  { text: "Très déçu, ça ne vaut pas le prix.", label: 1 },
  { text: "Je suis indigné par la qualité du produit.", label: 1 },
  { text: "C'est nul et cher, je regrette l'achat.", label: 1 },
  { text: "Je suis très frustré, ça ne répond pas à mes besoins.", label: 1 },
  { text: "C'est vraiment décevant, je ne reviendrai pas.", label: 1 },
  { text: "Je suis mécontent de l'expérience globale.", label: 1 },
  { text: "Terrible, je suis choqué par la mauvaise qualité.", label: 1 },
  { text: "C'est vraiment nul, je suis très déçu.", label: 1 },
  { text: "Je suis déçu et en colère, c'est inadmissible.", label: 1 },
  { text: "Ça ne fonctionne pas, je suis vraiment mécontent.", label: 1 },
  { text: "C'est une vraie arnaque, je suis scandalisé.", label: 1 },
  { text: "Je suis très insatisfait, vraiment décevant.", label: 1 },
  { text: "C'est de la mauvaise qualité, je regrette.", label: 1 },
  { text: "Je suis extrêmement déçu, c'est catastrophique.", label: 1 },
  { text: "Nul, je ne comprends pas comment on peut vendre ça.", label: 1 },
  { text: "C'est vraiment la honte, je suis déçu.", label: 1 },
  { text: "Je suis très en colère, ce produit est nul.", label: 1 },
  { text: "Vraiment horrible, je suis scandalisé.", label: 1 },
  { text: "Je regrette cet achat, c'est une perte de temps.", label: 1 },
  { text: "C'est déprimant à utiliser, vraiment nul.", label: 1 },
  { text: "Je suis très mécontent, ça ne tient pas ses promesses.", label: 1 },
  { text: "C'est un raté total, je suis déçu.", label: 1 },

  // ===== PHRASES NEUTRES (LABEL: 2) =====
  { text: "C'est un produit, rien de spécial.", label: 2 },
  { text: "Je ne sais pas, c'est difficile à dire.", label: 2 },
  { text: "C'est correct, rien de particulier.", label: 2 },
  { text: "OK, c'est normal.", label: 2 },
  { text: "Moyen, c'est pas mal pas pire.", label: 2 },
  { text: "C'est comme ci, c'est comme ça.", label: 2 },
  { text: "Acceptable, rien à redire.", label: 2 },
  { text: "Convenable, c'est standard.", label: 2 },
  { text: "Banal, c'est juste un truc normal.", label: 2 },
  { text: "Ordinaire, ni bon ni mauvais.", label: 2 },
  { text: "Basique, ça fait le job.", label: 2 },
  { text: "Régulier, rien d'exceptionnel.", label: 2 },
  { text: "C'est un service ordinaire.", label: 2 },
  { text: "Classique, comme les autres.", label: 2 },
  { text: "Standard, rien à objecter.", label: 2 },
  { text: "Courant, c'est la norme.", label: 2 },
  { text: "Habituel, sans surprise.", label: 2 },
  { text: "Commun, c'est normal.", label: 2 },
  { text: "Typique, rien d'étonnant.", label: 2 },
  { text: "Quelconque, c'est juste un truc.", label: 2 },
  { text: "Neutre, pas d'avis particulier.", label: 2 },
  { text: "C'est bon, c'est pas bon.", label: 2 },
  { text: "Peut être, je ne suis pas sûr.", label: 2 },
  { text: "Possible, difficile à juger.", label: 2 },
  { text: "Incertain, c'est flou.", label: 2 },
  { text: "Hésitant, je n'ai pas d'avis.", label: 2 },
  { text: "Ambigu, c'est complexe.", label: 2 },
  { text: "Confus, difficile à évaluer.", label: 2 },
  { text: "Opaque, c'est pas clair.", label: 2 },
  { text: "Vague, c'est indéfini.", label: 2 },
  { text: "Flou, difficile d'être précis.", label: 2 },
  { text: "C'est comme c'est, ni plus ni moins.", label: 2 },
  { text: "Tant pis, c'est comme ça.", label: 2 },
  { text: "C'est ce que c'est.", label: 2 },
  { text: "Bof, c'est un avis neutre.", label: 2 },
  { text: "Meh, c'est sans intérêt.", label: 2 },
  { text: "C'est facile à utiliser.", label: 2 },
  { text: "C'est une alternative possible.", label: 2 },
  { text: "C'est une option valide.", label: 2 },
  { text: "C'est acceptable dans l'ensemble.", label: 2 },
  { text: "C'est utilisable, rien de fou.", label: 2 },
  { text: "C'est correct pour le prix.", label: 2 },
  { text: "C'est approprié, c'est suffisant.", label: 2 },
  { text: "C'est adéquat, rien à réclamer.", label: 2 },
  { text: "C'est un bon choix neutre.", label: 2 },
  { text: "Je dirais que c'est correct.", label: 2 },
  { text: "C'est pas la meilleure, c'est pas la pire.", label: 2 },
  { text: "C'est moyen, je reste neutre.", label: 2 },
  { text: "C'est juste neutre, rien d'autre.", label: 2 },
  { text: "C'est un avis facile à comprendre.", label: 2 },
  { text: "Je l'utilise parfois, c'est fonctionnel.", label: 2 },
  { text: "C'est ni bien ni mal, juste passable.", label: 2 },
  { text: "Ça fait le travail, sans plus.", label: 2 },
  { text: "Je n'ai pas de préférence particulière.", label: 2 },
  { text: "C'est honnêtement dans la moyenne.", label: 2 },
  { text: "Je suis mitigé, il y a du bon et du mauvais.", label: 2 },
  { text: "C'est potable, sans être exceptionnel.", label: 2 },
  { text: "Je ne suis ni satisfait ni déçu.", label: 2 },
  { text: "C'est dans la moyenne des produits similaires.", label: 2 },
  { text: "Pas grand-chose à dire, c'est ordinaire.", label: 2 },
  { text: "Je l'ai essayé, c'est correct sans plus.", label: 2 },
  { text: "C'est suffisant pour un usage basique.", label: 2 },
  { text: "Je ne le recommande pas spécialement, mais ça peut aller.", label: 2 },
  { text: "C'est tout à fait normal, rien de remarquable.", label: 2 },
  { text: "Ni une catastrophe, ni une réussite.", label: 2 },
  { text: "C'est potable, mais sans enthousiasme.", label: 2 },
  { text: "Je suis assez indifférent à ce produit.", label: 2 },
  { text: "C'est passable, comme beaucoup d'autres.", label: 2 },
  { text: "Je n'ai pas d'opinion tranchée sur ce produit.", label: 2 },
  { text: "C'est raisonnable, rien de plus à dire.", label: 2 },
  { text: "Je suis mitigé, ça dépend des jours.", label: 2 },
  { text: "C'est dans la norme, sans surprises.", label: 2 },
  { text: "Je suis neutre, ça ne m'enthousiasme pas.", label: 2 },
  { text: "C'est correct mais pas mémorable.", label: 2 },
  { text: "Je n'ai rien de particulier à signaler.", label: 2 },
  { text: "C'est fonctionnel mais sans charme.", label: 2 },
  { text: "Je reste indécis sur la qualité.", label: 2 },
  { text: "C'est honnête mais sans plus.", label: 2 },
  { text: "Je suis partagé entre le positif et le négatif.", label: 2 },
  { text: "C'est dans la moyenne, pas plus.", label: 2 },
  { text: "Je ne suis ni pour ni contre.", label: 2 },
  { text: "C'est un produit lambda, sans originalité.", label: 2 },
  { text: "Je n'ai pas été touché dans un sens ou dans l'autre.", label: 2 },
  { text: "C'est convenable mais oubliable.", label: 2 },
  { text: "Je suis sans avis précis sur ce sujet.", label: 2 },
  { text: "C'est fonctionnel, c'est tout ce qu'on peut dire.", label: 2 },
  { text: "Je reste sur ma faim, mais ça peut convenir.", label: 2 },
  { text: "C'est acceptable pour une utilisation ponctuelle.", label: 2 },
  { text: "Je suis plutôt indifférent à ce que j'ai reçu.", label: 2 },
  { text: "C'est une option parmi d'autres, sans plus.", label: 2 },
  { text: "Je n'ai pas d'enthousiasme particulier pour ça.", label: 2 },
  { text: "C'est dans les clous, sans être brillant.", label: 2 },
  { text: "Je suis équilibré dans mon jugement.", label: 2 },
  { text: "C'est tout à fait moyen, sans surprise.", label: 2 },
  { text: "Je l'utilise faute de mieux, c'est correct.", label: 2 },
  { text: "C'est une expérience quelconque, pas mémorable.", label: 2 },
  { text: "Je suis sans passion pour ce produit.", label: 2 },
  { text: "C'est dans la bonne moyenne, sans plus.", label: 2 },
  { text: "Je n'ai pas de ressenti fort par rapport à ça.", label: 2 },
  { text: "C'est passable, je ne me plaindrais pas.", label: 2 },
  { text: "Je suis assez neutre dans mon évaluation.", label: 2 },
  { text: "C'est satisfaisant de façon basique.", label: 2 },
  { text: "Je suis sans enthousiasme, mais ça convient.", label: 2 },
  { text: "C'est dans les standards habituels.", label: 2 },
  { text: "Je reste dans l'expectative, ni déçu ni enchanté.", label: 2 },
  { text: "C'est tolérable, sans être remarquable.", label: 2 },
  { text: "Je suis neutre sur la question.", label: 2 },
  { text: "C'est tout à fait potable, sans excès.", label: 2 },
  { text: "Je n'ai rien à reprocher, mais rien à louer non plus.", label: 2 },
  { text: "C'est honnête dans sa proposition.", label: 2 },
  { text: "Je suis sans conviction forte sur ce produit.", label: 2 },
  { text: "C'est dans la bonne fourchette, sans exceller.", label: 2 },
  { text: "Je ne suis pas emballé, mais pas déçu non plus.", label: 2 },
  { text: "C'est une offre standard, rien de notable.", label: 2 },
  { text: "Je suis globalement neutre, ça se défend.", label: 2 },
  { text: "C'est satisfaisant au sens basique du terme.", label: 2 },
  { text: "Je suis sans opinion particulière sur le sujet.", label: 2 },
  { text: "C'est un produit quelconque, dans la norme.", label: 2 },
  { text: "Je suis mitigé, sans être vraiment déçu.", label: 2 },
  { text: "C'est raisonnable, sans être exceptionnel.", label: 2 },
  { text: "Je reste neutre, c'est correct.", label: 2 },
  { text: "C'est dans l'honnête, rien de plus.", label: 2 },
  { text: "Je suis sans passion, mais sans déception.", label: 2 },
  { text: "C'est acceptable, je ne me plains pas.", label: 2 },
  { text: "Je n'ai pas de position tranchée.", label: 2 },
  { text: "C'est du déjà vu, sans originalité.", label: 2 },
  { text: "Je suis ni emballé ni déçu.", label: 2 },
  { text: "C'est dans la normale, sans surprises.", label: 2 },
  { text: "Je suis sans avis fort, c'est moyen.", label: 2 },
  { text: "C'est standard et sans prétention.", label: 2 },
  { text: "Je suis indécis, c'est dans la moyenne.", label: 2 },
  { text: "C'est ni brillant ni mauvais.", label: 2 },
  { text: "Je suis sans préférence, ça se vaut.", label: 2 },
  { text: "C'est une expérience banale, sans impact.", label: 2 },
  { text: "Je n'ai pas d'opinion arrêtée.", label: 2 },
  { text: "C'est médiocre dans le bon sens du terme.", label: 2 },
  { text: "Je suis sans enthousiasme ni hostilité.", label: 2 },
  { text: "C'est tout à fait dans la norme.", label: 2 },
  { text: "Je reste neutre, c'est convenable.", label: 2 },
  { text: "C'est sans relief, mais fonctionnel.", label: 2 },
  { text: "Je suis indifférent à ce produit.", label: 2 },
  { text: "C'est honnêtement quelconque.", label: 2 },
  { text: "Je n'ai ni bonnes ni mauvaises impressions.", label: 2 },
  { text: "C'est dans la bonne moyenne, acceptable.", label: 2 },
  { text: "Je suis neutre sur cette expérience.", label: 2 },
  { text: "C'est potable, rien à signaler de particulier.", label: 2 },
  { text: "Je suis sans réaction forte, c'est normal.", label: 2 },
  { text: "C'est dans les standards du marché.", label: 2 },
  { text: "Je n'ai pas de sentiment tranché sur ce sujet.", label: 2 },
  { text: "C'est correct dans l'ensemble, sans exceller.", label: 2 },
];

/**
 * Fonction utilitaire pour accéder au dataset
 * @returns {Array} - Copie du dataset original (immutable)
 */
export function getDataset() {
  return [...sentimentDataset];
}

/**
 * Fonction utilitaire pour compter les phrases par classe
 * @returns {Object} - { positif, négatif, neutre, total }
 */
export function getDatasetStats() {
  const counts = { positif: 0, négatif: 0, neutre: 0 };
  sentimentDataset.forEach((sample) => {
    if (sample.label === 0) counts.positif++;
    else if (sample.label === 1) counts.négatif++;
    else if (sample.label === 2) counts.neutre++;
  });
  return {
    positif: counts.positif,
    négatif: counts.négatif,
    neutre: counts.neutre,
    total: sentimentDataset.length,
  };
}

/**
 * Fonction pour mélanger le dataset (utile avant train/test split)
 * @returns {Array} - Dataset mélangé
 */
export function shuffleDataset() {
  const shuffled = [...sentimentDataset];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }
  return shuffled;
}