export const DECISION_ACTIONS = {
  DO_NOTHING: 'DO_NOTHING',
  LOG_RISK: 'LOG_RISK',
  OFFER_DISCOUNT_SMALL: 'OFFER_DISCOUNT_SMALL',
  OFFER_DISCOUNT_AGGRESSIVE: 'OFFER_DISCOUNT_AGGRESSIVE',
};

export const PRIORITY_LEVELS = {
  HIGH: 2,
  MEDIUM: 1,
  LOW: 0,
};
